--- 
title: "Penyebab stres Mahasiswa"
author: "Kevin"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: 
description: ""
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(.packages(), 'bookdown', 'knitr', 'rmarkdown'), 'packages.bib')
```

# Abstrak
<div style="text-align: justify"> 
Saat ini banyak Mahasiswa mengalami stres di beberapa kota,untuk itu kami melakukan penelitian terhadap penyebab stres yg dialami Mahasiswa.


**Kata kunci:** Modern portfolio theory, Portfolio Optimization, Efficient Frontier, R Language 
</div>




# Kata Pengantar
<div style="text-align: justify"> 
Puji syukur senantiasa kita panjatkan kehadirat Tuhan Yang Maha Esa atas semua limpahan rahmat-Nya sehingga tim dan saya dapat menyelesaikan penyusunan buku yang berjudul **"Metode Penelitian"**, meskipun dengan sangat sederhana. Harapan kami, kirannya buku yang telah tersusun ini dapat bermanfaat menjadi salah satu rujukan maupun pedoman bagi para pembaca, menambah wawasan serta dapat menjadi inspirasi dalam memahami ilmu statistik.  

Sebagai penulis, saya **Bakti Siregar M.Sc** mengakui bahwasanya masih banyak kekurangan yang terkandung di dalamnya. Oleh sebab itu, dengan penuh kerendahan hati saya berharap kepada para pembaca untuk memberikan kritik dan saran demi lebih memperbaiki buku ini.

Tidak lupa, penulis juga mengucapkan terima kasih kepada semua pihak yang telah berjasa memberikan kontribusi dalam rangka menyelesaikan buku ini, yaitu kepada mahasiswa saya di Program Studi Statistika Matana University: 

> 1. Endri Tri Wibowo (alamat email)
> 2. Jihan Selianovira alamat email)
> 3. Kevin Sugianto (alamat email)
> 4. Ardiwan (alamat email)

<br>
**Tentang Penulis:**
<br>
Email      : siregarbakti@gmail.com / siregar.bakti@matanauniversity.ac.id <br>
No.Whatsapp: 081369552544

</div>






